# Site settings
title: Crj Blog
SEOTitle: 力Q的博客 | Crj Blog
header-img: img/home-bg.jpg
email: ruijunchen26@gmail.com
description:
keyword: "java"
url: "https://ruijunchen.github.io"      # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true